# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ new ]
  pull_request:
    branches: [ new ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Meet-a-stranger.Websocket

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
            
    steps:
      - uses: actions/checkout@v2
      - name: Add remote origin
        run: git remote add heroku-websocket https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_WEBSOCKET_APP_NAME }}.git
      - name: Deploy to heroku
        run: git push heroku-websocket `git subtree split --prefix Meet-a-stranger.Websocket new`:refs/heads/master --force
    
